# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CommonResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, code: str=None, message: str=None, info: List[str]=None):  # noqa: E501
        """CommonResponse - a model defined in Swagger

        :param code: The code of this CommonResponse.  # noqa: E501
        :type code: str
        :param message: The message of this CommonResponse.  # noqa: E501
        :type message: str
        :param info: The info of this CommonResponse.  # noqa: E501
        :type info: List[str]
        """
        self.swagger_types = {
            'code': str,
            'message': str,
            'info': List[str]
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message',
            'info': 'info'
        }

        self._code = code
        self._message = message
        self._info = info

    @classmethod
    def from_dict(cls, dikt) -> 'CommonResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CommonResponse of this CommonResponse.  # noqa: E501
        :rtype: CommonResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> str:
        """Gets the code of this CommonResponse.

        Result  # noqa: E501

        :return: The code of this CommonResponse.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this CommonResponse.

        Result  # noqa: E501

        :param code: The code of this CommonResponse.
        :type code: str
        """
        allowed_values = ["OK", "NG"]  # noqa: E501
        if code not in allowed_values:
            raise ValueError(
                "Invalid value for `code` ({0}), must be one of {1}"
                .format(code, allowed_values)
            )

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this CommonResponse.

        Addition message  # noqa: E501

        :return: The message of this CommonResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this CommonResponse.

        Addition message  # noqa: E501

        :param message: The message of this CommonResponse.
        :type message: str
        """

        self._message = message

    @property
    def info(self) -> List[str]:
        """Gets the info of this CommonResponse.


        :return: The info of this CommonResponse.
        :rtype: List[str]
        """
        return self._info

    @info.setter
    def info(self, info: List[str]):
        """Sets the info of this CommonResponse.


        :param info: The info of this CommonResponse.
        :type info: List[str]
        """

        self._info = info
