# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ExchangeRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, exchange_code: str=None, primary_key: str=None, secret_key: str=None, password: str=None):  # noqa: E501
        """ExchangeRequest - a model defined in Swagger

        :param exchange_code: The exchange_code of this ExchangeRequest.  # noqa: E501
        :type exchange_code: str
        :param primary_key: The primary_key of this ExchangeRequest.  # noqa: E501
        :type primary_key: str
        :param secret_key: The secret_key of this ExchangeRequest.  # noqa: E501
        :type secret_key: str
        :param password: The password of this ExchangeRequest.  # noqa: E501
        :type password: str
        """
        self.swagger_types = {
            'exchange_code': str,
            'primary_key': str,
            'secret_key': str,
            'password': str
        }

        self.attribute_map = {
            'exchange_code': 'exchange_code',
            'primary_key': 'primary_key',
            'secret_key': 'secret_key',
            'password': 'password'
        }

        self._exchange_code = exchange_code
        self._primary_key = primary_key
        self._secret_key = secret_key
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'ExchangeRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExchangeRequest of this ExchangeRequest.  # noqa: E501
        :rtype: ExchangeRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def exchange_code(self) -> str:
        """Gets the exchange_code of this ExchangeRequest.

        Exchange code  # noqa: E501

        :return: The exchange_code of this ExchangeRequest.
        :rtype: str
        """
        return self._exchange_code

    @exchange_code.setter
    def exchange_code(self, exchange_code: str):
        """Sets the exchange_code of this ExchangeRequest.

        Exchange code  # noqa: E501

        :param exchange_code: The exchange_code of this ExchangeRequest.
        :type exchange_code: str
        """

        self._exchange_code = exchange_code

    @property
    def primary_key(self) -> str:
        """Gets the primary_key of this ExchangeRequest.

        primary key  # noqa: E501

        :return: The primary_key of this ExchangeRequest.
        :rtype: str
        """
        return self._primary_key

    @primary_key.setter
    def primary_key(self, primary_key: str):
        """Sets the primary_key of this ExchangeRequest.

        primary key  # noqa: E501

        :param primary_key: The primary_key of this ExchangeRequest.
        :type primary_key: str
        """

        self._primary_key = primary_key

    @property
    def secret_key(self) -> str:
        """Gets the secret_key of this ExchangeRequest.

        secret key  # noqa: E501

        :return: The secret_key of this ExchangeRequest.
        :rtype: str
        """
        return self._secret_key

    @secret_key.setter
    def secret_key(self, secret_key: str):
        """Sets the secret_key of this ExchangeRequest.

        secret key  # noqa: E501

        :param secret_key: The secret_key of this ExchangeRequest.
        :type secret_key: str
        """

        self._secret_key = secret_key

    @property
    def password(self) -> str:
        """Gets the password of this ExchangeRequest.

        password  # noqa: E501

        :return: The password of this ExchangeRequest.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this ExchangeRequest.

        password  # noqa: E501

        :param password: The password of this ExchangeRequest.
        :type password: str
        """

        self._password = password
