# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ExchangeRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, code: str=None, primary_key: str=None):  # noqa: E501
        """ExchangeRequest - a model defined in Swagger

        :param code: The code of this ExchangeRequest.  # noqa: E501
        :type code: str
        :param primary_key: The primary_key of this ExchangeRequest.  # noqa: E501
        :type primary_key: str
        """
        self.swagger_types = {
            'code': str,
            'primary_key': str
        }

        self.attribute_map = {
            'code': 'code',
            'primary_key': 'primary_key'
        }

        self._code = code
        self._primary_key = primary_key

    @classmethod
    def from_dict(cls, dikt) -> 'ExchangeRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExchangeRequest of this ExchangeRequest.  # noqa: E501
        :rtype: ExchangeRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> str:
        """Gets the code of this ExchangeRequest.

        Exchange code  # noqa: E501

        :return: The code of this ExchangeRequest.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this ExchangeRequest.

        Exchange code  # noqa: E501

        :param code: The code of this ExchangeRequest.
        :type code: str
        """

        self._code = code

    @property
    def primary_key(self) -> str:
        """Gets the primary_key of this ExchangeRequest.

        Exchange primary  # noqa: E501

        :return: The primary_key of this ExchangeRequest.
        :rtype: str
        """
        return self._primary_key

    @primary_key.setter
    def primary_key(self, primary_key: str):
        """Sets the primary_key of this ExchangeRequest.

        Exchange primary  # noqa: E501

        :param primary_key: The primary_key of this ExchangeRequest.
        :type primary_key: str
        """

        self._primary_key = primary_key
