# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LoginRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, login_id: int=None, password: str=None):  # noqa: E501
        """LoginRequest - a model defined in Swagger

        :param login_id: The login_id of this LoginRequest.  # noqa: E501
        :type login_id: int
        :param password: The password of this LoginRequest.  # noqa: E501
        :type password: str
        """
        self.swagger_types = {
            'login_id': int,
            'password': str
        }

        self.attribute_map = {
            'login_id': 'login_id',
            'password': 'password'
        }

        self._login_id = login_id
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'LoginRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoginRequest of this LoginRequest.  # noqa: E501
        :rtype: LoginRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def login_id(self) -> int:
        """Gets the login_id of this LoginRequest.

        Login ID  # noqa: E501

        :return: The login_id of this LoginRequest.
        :rtype: int
        """
        return self._login_id

    @login_id.setter
    def login_id(self, login_id: int):
        """Sets the login_id of this LoginRequest.

        Login ID  # noqa: E501

        :param login_id: The login_id of this LoginRequest.
        :type login_id: int
        """

        self._login_id = login_id

    @property
    def password(self) -> str:
        """Gets the password of this LoginRequest.

        Password  # noqa: E501

        :return: The password of this LoginRequest.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this LoginRequest.

        Password  # noqa: E501

        :param password: The password of this LoginRequest.
        :type password: str
        """

        self._password = password
